name: Sync upstream

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sync upstream
        uses: enterprise-actions/sync-upstream@v1.0.0
        with:
          upstream-repo: Vision-CAIR/MiniGPT-4
          upstream-branch: main
          fork-repo: Carlelst/MiniGPT-4
          fork-branch: main
          oauth-token: ${{ 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 }}
