name: Sync Fork

on:
  push:
    branches:
      - main
  schedule:
    - cron: '1 0 * * *' # 对于一些更新不那么频繁的项目可以设置为每天一次, 低碳一点

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: zwping/fork-sync@v1.6.5
        with:
          #token: ${{ github.token }}
          github_token: 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 
          owner: Vision-CAIR # fork 的上游仓库 user
          head: main # fork 的上游仓库 branch
          base: main # 本地仓库 branch
          

