name: Sync Fork

on:
  push:
    branches:
      - main
  schedule:
    - cron: '* * */1 * *' # 对于一些更新不那么频繁的项目可以设置为每天一次, 低碳一点

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.2.1
        with:
          oauth-token: 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 
          owner: Vision-CAIR # fork 的上游仓库 user
          head: main # fork 的上游仓库 branch
          base: main # 本地仓库 branch
          

