name: Sync Fork

on:
  push:
    branches:
      - main
  schedule:
    - cron: '* * */1 * *' # 对于一些更新不那么频繁的项目可以设置为每天一次, 低碳一点

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: TG908/fork-sync@v1.6.3
        with:
          upstream-repo: Vision-CAIR/MiniGPT-4
          upstream-branch: main
          fork-repo: Carlelst/MiniGPT-4
          fork-branch: main
          oauth-token: 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 
          

